--- #local
spring:
  config:
    activate:
      on-profile: local

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/eatthis?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&verifyServerCertificate=false&useSSL=false
    username: root
    password: root1234
    hikari:
      poolName: Hikari
      maximum-pool-size: 10
      max-lifetime: 1800000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

logging:
  level:
    org.springframework.web: info
    site.heeseong: info
    org.hibernate.type: trace
    org.hibernate.SQL: trace
  file:
    name: ${file.separator}logs${file.separator}restdocs${file.separator}restdocs$.log
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 10MB
